# Rustfmt Configuration for Xeno
# See: https://rust-lang.github.io/rustfmt/

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"

# Code style
newline_style = "Unix"
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true

# Control flow
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"

# Functions and structs
fn_args_layout = "Tall"
where_single_line = true

# Comments and documentation
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# String formatting
format_strings = true

# Misc
trailing_comma = "Vertical"
trailing_semicolon = true
space_before_colon = false
space_after_colon = true