# Rustfmt Configuration for Xeno (Stable-compatible)
# See: https://rust-lang.github.io/rustfmt/

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Code style (stable features only)
newline_style = "Unix"
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true

# Functions and structs (stable features only)
fn_params_layout = "Tall"