use serde_json::json;

fn main() {
    println!("Xeno OpenAPI Generator");
    println!("This tool will generate OpenAPI specifications from Xeno applications");
    
    // Placeholder OpenAPI document
    let openapi_doc = json!({
        "openapi": "3.0.0",
        "info": {
            "title": "Xeno API",
            "version": "1.0.0",
            "description": "API generated by Xeno framework"
        },
        "paths": {
            "/": {
                "get": {
                    "summary": "Hello World",
                    "responses": {
                        "200": {
                            "description": "Success",
                            "content": {
                                "text/plain": {
                                    "schema": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "/health": {
                "get": {
                    "summary": "Health Check",
                    "responses": {
                        "200": {
                            "description": "Health check response",
                            "content": {
                                "text/plain": {
                                    "schema": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    });
    
    println!("{}", serde_json::to_string_pretty(&openapi_doc).unwrap());
}